[package]
name = "sajit"
description = "Sa Programming Language Just-In-Time Loader"
version = "0.0.1"
edition = "2024"

[dependencies]
memmap2 = "0.9"

[target.'cfg(all(target_os="linux", not(target_arch = "x86_64")))'.dependencies]
clear-cache = "0.1"

[dev-dependencies]
cranelift = { version = "0.128", features = ["native"] }

[features]
aarch64 = []
